services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart   # sincroniza o app principal e reinicia o CMD
          path: ./main.cpp
          target: /app/main.cpp

        - action: sync+restart   # código e headers da VM
          path: ./vm
          target: /app/vm
    
        - action: sync+restart   # pasta de jogo mantida no layout real
          path: ./game
          target: /app/game

        - action: rebuild        # mudança nas regras de build exige nova imagem
          path: Makefile

        - action: rebuild
          path: Dockerfile